name: Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pytest
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest test_app.py
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ulaania/lab_7:latest
